#!/bin/bash

# Copyright (c) 2012-2014 CloudOS Huawei, China.

#
# /etc/init.d/had
#
#   and symbolic its link
#
# /usr/sbin/rcvem
#
# chkconfig: 35 85 60
# description: ha service
# processname: had

### BEGIN INIT INFO
# Provides: had
# Required-Start: network cron
# Required-Stop: network
# Default-Start: 3 5
# Default-Stop: 0 1 2 6
# Description: Start the had daemon
### END INIT INFO

#need Galax install path
. /etc/profile 2>/dev/null
HA_BIN=$HA_DIR/tools/had.sh
test -x $HA_BIN || exit 5

# Shell functions sourced from /etc/rc.status:
#      rc_check         check and set local and overall rc status
#      rc_status        check and set local and overall rc status
#      rc_status -v     ditto but be verbose in local rc status
#      rc_status -v -r  ditto and clear the local rc status
#      rc_failed        set local and overall rc status to failed
#      rc_reset         clear local rc status (overall remains)
#      rc_exit          exit appropriate to overall rc status

. $HA_BIN


case "$1" in
    start)
        echo "Starting ha daemon"
        ## Call do_start in had.sh
        do_start

        ;;
    stop)
        echo "Shutting down ha daemon"
        ## Call do_stop in had.sh
        do_stop

        ;;
    try-restart)
        ## Stop the service and if this succeeds (i.e. the
        ## service was running before), start it again.
        $0 status >/dev/null && $0 restart

        ;;
    restart)
        ## Stop the service and regardless of whether it was
        ## running or not, start it again.
        $0 stop
        $0 start

        ;;
    force-reload|reload)
        ## Signal the daemon to reload its config. Most daemons
        ## do this on signal 1 (SIGHUP).

        echo -n "Not Support Reload service had"
        ;;
    status)
        ## Check status with checkproc(8), if process is running
        ## checkproc will return with exit status 0.

        # Status has a slightly different for the status command:
        # 0 - service running
        # 1 - service dead, but /var/run/  pid  file exists
        # 2 - service dead, but /var/lock/ lock file exists
        # 3 - service not running
        echo "Checking for service had"

        do_status
        if [ $? -ne 0 ]; then
            rc_failed 3
        fi
        ;;
    query)
        do_query
        ;;
    probe)
        ## Optional: Probe for the necessity of a reload,
        ## give out the argument which is required for a reload.

        #test /etc/demo/demo_config -nt $DEMO_PIDFILE && echo reload
        ;;
        *)
        echo "Usage: $0 {start|stop|status|query|try-restart|restart|probe}"
        exit 1
        ;;
esac
